# 5주차 스터디

Made by 35기 코딩부장 류제현

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. Pandas Apply 사용과 정규표현식(Regular Expression)

Spam 메일 데이터 셋을 사용하겠습니다

In [11]:
# 데이터를 불러옵니다
spam = pd.read_csv("Data/spam.csv")

spam

text target
0     Go until jurong point, crazy.. Available only ...    ham
1                         Ok lar... Joking wif u oni...    ham
2     Free entry in 2 a wkly comp to win FA Cup fina...   spam
3     U dun say so early hor... U c already then say...    ham
4     Nah I don't think he goes to usf, he lives aro...    ham
...                                                 ...    ...
5567  This is the 2nd time we have tried 2 contact u...   spam
5568              Will Ì_ b going to esplanade fr home?    ham
5569  Pity, * was in mood for that. So...any other s...    ham
5570  The guy did some bitching but I acted like i'd...    ham
5571                         Rofl. Its true to its name    ham

[5572 rows x 2 columns]

In [12]:
# np.where(조건, 참일 경우, 거짓일 경우)
# 정답지(target)을 1과 0으로 변경 (머신러닝 모델을 짜고 싶다면 이렇게 변경해야 한다)
spam['target'] = np.where(spam['target']=='spam',1,0)

# 이 셀을 두 번 실행시키면 값이 달라지는데 그 이유는 아시겠죠?
spam

text  target
0     Go until jurong point, crazy.. Available only ...       0
1                         Ok lar... Joking wif u oni...       0
2     Free entry in 2 a wkly comp to win FA Cup fina...       1
3     U dun say so early hor... U c already then say...       0
4     Nah I don't think he goes to usf, he lives aro...       0
...                                                 ...     ...
5567  This is the 2nd time we have tried 2 contact u...       1
5568              Will Ì_ b going to esplanade fr home?       0
5569  Pity, * was in mood for that. So...any other s...       0
5570  The guy did some bitching but I acted like i'd...       0
5571                         Rofl. Its true to its name       0

[5572 rows x 2 columns]

spam의 문자열 수와, non_spam의 문자열 개수의 평균을 구해봅시다

In [30]:
# apply에 함수를 넣어주는데 지금까지 우리는 우리가 만들어준 함수인 lambda를 넣어줬습니다
## 하지만, len과 같은 파이썬 내장 함수도 적용할 수 있습니다
avg_0 = spam.loc[spam.target == 0]["text"].apply(len).mean()
avg_1 = spam.loc[spam.target == 1]["text"].apply(len).mean()

In [33]:
# 결과를 확인해봅시다
avg_0, avg_1

(71.02362694300518, 138.8661311914324)

    Spam과 Non Spam 메일에 숫자가 평균적으로 몇 번 들어가 있을까요

정규표현식 소개 (Regular Expression)

* import re

* 자연어처리(NLP)를 할 때 매우 유용하게 사용함

* 단어의 규칙, 뭉치 등을 찾아올 때 편하다

* 정규표현식 하나만으로도 책 한권이 나오는 분량입니다. 이런게 있다고만 알고 계시고, 나중에 필요할 때 공부하시면 될 것 같습니다

In [39]:
# 이 문자열에서 가격만 추출해볼까요?
string = "한 주당 1,000원, 시가총액은 300,000,000원입니다"

In [38]:
# Regular Expression 모듈은 import re로 불러올 수 있습니다
import re

# re에는 여러 함수가 있는데, 그 중에서도 규칙에 맞는 모든 단어를 찾아오는 findall 함수를 사용해 보겠습니다
re.findall("[0-9,]+원", string)

## [0-9,] -> 0과 9사이의 모든 숫자 그리고 쉼표(,)를 찾아오라는 의미 
## +      -> More than One
## 원     -> "원"

['1,000원', '300,000,000원']

In [41]:
# Spam 매일과 Non-spam 매일에 들어있는 숫자의 개수를 구해봅시다

spam["text"]
## 여기에 정규표현식을 이용한 함수를 만들어서 apply에 넣어주면 되겠죠?

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: text, Length: 5572, dtype: object

In [44]:
# 함수를 짜줍시다
def count_digit(x): # x가 하나의 메일 text가 된다 (lambda x: 의 x와 동일하다고 생각하면 된다)
    pure_digit = re.findall('[0-9]',x) 
    len_digit = len(pure_digit)
    return len_digit

In [49]:
# apply에 넣어줍시다
digit_0 = spam.loc[spam.target == 0]["text"].apply(count_digit)
digit_1 = spam.loc[spam.target == 1]["text"].apply(count_digit)

# 개수의 평균을 구해봅시다 -> spam 메일이 숫자가 많이 들어가 있군요
digit_0.mean(), digit_1.mean()

(0.2992746113989637, 15.759036144578314)

정리) 새로 배운거

1. np.where -> 퀀트에서도 많이 씀

2. Regular Expression

3. apply에 직접 짠 함수 넣기

## Machine Learning Basic 2

지난주 수업에 이어서 scikit-learn을 사용한 머신러닝을 배워보겠습니다

주가를 예측하는 간단한 머신러닝 모델을 만들어 보겠습니다

In [57]:
# 데이터셋을 불러오겠습니다
df = pd.read_csv("Data/coin_prediction.csv", index_col=0,
                  parse_dates=True)
df

# 고려할 점은 많지만, 단순화를 위해 복잡한 상황은 고려하지 않겠습니다
## 여러 변수로 다음날 BTC 가격을 예측하는 머신러닝 모델을 짜보겠습니다

BTC         NYSE        NASDAQ     LSE    BTC_Volume  \
Date                                                                       
2018-01-02  14982.09961  12902.71973   7006.899902  3742.0  1.684660e+10   
2018-01-03  15201.00000  12957.28027   7065.529785  3749.0  1.687190e+10   
2018-01-04  15599.20020  13028.45996   7077.910156  3749.0  2.178320e+10   
2018-01-05  17429.50000  13103.23047   7136.560059  3758.0  2.384090e+10   
2018-01-08  15170.09961  13114.34961   7157.390137  3744.0  1.841390e+10   
...                 ...          ...           ...     ...           ...   
2022-12-23  16796.95313  15188.45020  10497.860350  7130.0  1.532927e+10   
2022-12-27  16717.17383  15218.25977  10353.230470  7130.0  1.574858e+10   
2022-12-28  16552.57227  15037.32031  10213.290040  7128.0  1.700571e+10   
2022-12-29  16642.34180  15241.20996  10478.089840  7212.0  1.447224e+10   
2022-12-30  16602.58594  15184.30957  10466.480470  7136.0  1.592916e+10   

            NYSE_Volume  NASDAQ_Volume  LSE_Volume  
Date                                                
2018-01-02   3397430000     1929700000      497857  
2018-01-03   3544030000     2173130000     1009997  
2018-01-04   3697340000     2103220000      669448  
2018-01-05   3239280000     2024000000     2225274  
2018-01-08   3246160000     2055010000      930995  
...                 ...            ...         ...  
2022-12-23   2819280000     3544680000      141614  
2022-12-27   3030300000     3827290000      141614  
2022-12-28   3083520000     3842970000      490323  
2022-12-29   3003680000     4154100000      457006  
2022-12-30   2979870000     3959030000      226505  

[1259 rows x 8 columns]

In [59]:
# 우선 정답지를 만들어 주겠습니다
## BTC가 "다음 날" 오르면 1, 내리면 0으로 정답을 설정하겠습니다
df.BTC.pct_change()

Date
2018-01-02         NaN
2018-01-03    0.014611
2018-01-04    0.026196
2018-01-05    0.117333
2018-01-08   -0.129631
                ...   
2022-12-23   -0.001984
2022-12-27   -0.004750
2022-12-28   -0.009846
2022-12-29    0.005423
2022-12-30   -0.002389
Name: BTC, Length: 1259, dtype: float64

In [11]:
# 결측치 있는 지 확인
X.isnull().sum().sum() , y.isna().sum().sum()   # na와 null은 동일하다, 둘 중 하나가 더 익숙한 사람을 위해 만들어 둔 것

(0, 0)

In [12]:
# 훈련셋과 테스트 셋 분리해주기
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y_binary, train_size=0.8) # default 0.75
X_train.shape, X_test.shape

((142, 13), (36, 13))

### 분류기 평가 Metric 


* 정확도 / 정밀도 / 재현율

In [13]:
# 간단하게 모형 만들어보기
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train) 

DecisionTreeClassifier()

In [14]:
# Tree기반 모델은 변수 중요도(feature_importance)를 확인할 수 있습니다
tree_model.feature_importances_

array([0.12854147, 0.        , 0.02865278, 0.        , 0.01884874,
       0.        , 0.        , 0.        , 0.        , 0.70258949,
       0.04045584, 0.08091168, 0.        ])

In [15]:
tree_model.feature_names_in_ # petal은 꽃잎

array(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'], dtype=object)

In [16]:
# 분류기의 경우에 score는 단순한 정확도를 리턴 (accuracy score)
tree_model.score(X_train, y_train)

# 단일 Tree는 무조건 오버피팅 하기 때문에, 정확도가 1.0이 나오는 것을 확인할 수 있다.

1.0

In [17]:
# test-set에 대한 점수를 확인해 봅시다
tree_model.score(X_test,y_test)

1.0

목표로 하는 task에 따라서 중요하게 생각해야하는 Metric이 달라진다 (통계학의 1종오류, 2종오류 개념과 유사)

* 정확도(Accuracy)  : 전체 데이터 수 중 예측 결과와 실제 값이 동일한 건수(TN + TP)가 차지하는 비율

* 정밀도(Precision) : 예측을 Positive로 한 대상(FP + TP) 중 예측과 실제 값이 Positive로 일치한 데이터(TP)의 비율

* 재현율(Recall) : 실제가 Positive인 대상(FN + TP) 중 예측과 실제 값이 Positive로 일치한 데이터(TP)의 비율



In [18]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,
                 tree_model.predict(X_test)) # 실제는 positive인데, 예측을 negative로 한 값이 하나 존재한다

array([[17,  0],
       [ 0, 19]], dtype=int64)

In [19]:
# 분류의 경우 정확도 말고도 사용할 수 있는 다양한 성능평가 지표들이 있습니다. 
## 그 중에서 정밀도와 재현율을 배워보겠습니다

from sklearn.metrics import precision_score, recall_score

print("모델의 정확도: ", tree_model.score(X_test,y_test))
print("모델의 정밀도: ", precision_score(y_test, tree_model.predict(X_test)))
print("모델의 재현율: ", recall_score(y_test, tree_model.predict(X_test)))

모델의 정확도:  1.0
모델의 정밀도:  1.0
모델의 재현율:  1.0


### Cross-Validation

* Test-set을 미리 들여다 보는 우를 범하지 않기 위해 사용함

In [20]:
# 훈련하고 성과 측정하기 
from sklearn.model_selection import cross_val_score

tree_model = DecisionTreeClassifier()

# cv=5이면 데이터를 5번 쪼갠다. 데이터는 반드시 Random해야 한다!
cv_score = cross_val_score(tree_model, X_train, y_train, 
                           cv=5, n_jobs=-1, verbose=True)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    3.5s finished


In [21]:
print(cv_score)

# cv_score의 평균
cv_score.mean()

[0.93103448 0.82758621 0.89285714 0.96428571 0.96428571]


0.9160098522167488

### Grid-Search 

* Grid-Search
* Random-search

In [22]:
from sklearn.model_selection import GridSearchCV

tree_model = DecisionTreeClassifier()

param_grid = {"criterion" : ["gini","entropy"],  
              'max_depth': [10,20,30,40,50]} 

model_reg = GridSearchCV(tree_model, param_grid, 
                         cv=10, verbose=True, n_jobs=-1)
model_reg.fit(X_train,y_train)

model_reg.best_params_

Fitting 10 folds for each of 10 candidates, totalling 100 fits


{'criterion': 'gini', 'max_depth': 40}

In [23]:
model_reg.score(X_train, y_train)

1.0

In [24]:
# Random Search
from sklearn.model_selection import RandomizedSearchCV

random_forest = DecisionTreeClassifier()
param_grid = {'max_depth':range(10,40)}

random_reg = RandomizedSearchCV(random_forest, param_grid, n_iter=10, 
                                cv=5, n_jobs=-1, verbose=True)
random_reg.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
                   param_distributions={'max_depth': range(10, 40)},
                   verbose=True)

In [25]:
random_reg.best_estimator_

DecisionTreeClassifier(max_depth=35)