# 5주차 스터디

Made by 35기 코딩부장 류제현

In [1]:
import numpy as npa
import pandas as pd
import matplotlib.pyplot as plt

## 1. Pandas Apply 사용과 정규표현식(Regular Expression)

Spam 메일 데이터 셋을 사용하겠습니다

In [2]:
# 데이터를 불러옵니다
spam = pd.read_csv("Data/spam.csv")

spam

text target
0     Go until jurong point, crazy.. Available only ...    ham
1                         Ok lar... Joking wif u oni...    ham
2     Free entry in 2 a wkly comp to win FA Cup fina...   spam
3     U dun say so early hor... U c already then say...    ham
4     Nah I don't think he goes to usf, he lives aro...    ham
...                                                 ...    ...
5567  This is the 2nd time we have tried 2 contact u...   spam
5568              Will Ì_ b going to esplanade fr home?    ham
5569  Pity, * was in mood for that. So...any other s...    ham
5570  The guy did some bitching but I acted like i'd...    ham
5571                         Rofl. Its true to its name    ham

[5572 rows x 2 columns]

In [3]:
# np.where(조건, 참일 경우, 거짓일 경우)
# 정답지(target)을 1과 0으로 변경 (머신러닝 모델을 짜고 싶다면 이렇게 변경해야 한다)
spam['target'] = np.where(spam['target']=='spam',1,0)

# 이 셀을 두 번 실행시키면 값이 달라지는데 그 이유는 아시겠죠?
spam

text  target
0     Go until jurong point, crazy.. Available only ...       0
1                         Ok lar... Joking wif u oni...       0
2     Free entry in 2 a wkly comp to win FA Cup fina...       1
3     U dun say so early hor... U c already then say...       0
4     Nah I don't think he goes to usf, he lives aro...       0
...                                                 ...     ...
5567  This is the 2nd time we have tried 2 contact u...       1
5568              Will Ì_ b going to esplanade fr home?       0
5569  Pity, * was in mood for that. So...any other s...       0
5570  The guy did some bitching but I acted like i'd...       0
5571                         Rofl. Its true to its name       0

[5572 rows x 2 columns]

spam의 문자열 수와, non_spam의 문자열 개수의 평균을 구해봅시다

In [4]:
# apply에 함수를 넣어주는데 지금까지 우리는 우리가 만들어준 함수인 lambda를 넣어줬습니다
## 하지만, len과 같은 파이썬 내장 함수도 적용할 수 있습니다
avg_0 = spam.loc[spam.target == 0]["text"].apply(len).mean()
avg_1 = spam.loc[spam.target == 1]["text"].apply(len).mean()

In [5]:
# 결과를 확인해봅시다
avg_0, avg_1

(71.02362694300518, 138.8661311914324)

    Spam과 Non Spam 메일에 숫자가 평균적으로 몇 번 들어가 있을까요

정규표현식 소개 (Regular Expression)

* import re

* 자연어처리(NLP)를 할 때 매우 유용하게 사용함

* 단어의 규칙, 뭉치 등을 찾아올 때 편하다

* 정규표현식 하나만으로도 책 한권이 나오는 분량입니다. 이런게 있다고만 알고 계시고, 나중에 필요할 때 공부하시면 될 것 같습니다

In [6]:
# 이 문자열에서 가격만 추출해볼까요?
string = "한 주당 1,000원, 시가총액은 300,000,000원입니다"

In [7]:
# Regular Expression 모듈은 import re로 불러올 수 있습니다
import re

# re에는 여러 함수가 있는데, 그 중에서도 규칙에 맞는 모든 단어를 찾아오는 findall 함수를 사용해 보겠습니다
re.findall("[0-9,]+원", string)

## [0-9,] -> 0과 9사이의 모든 숫자 그리고 쉼표(,)를 찾아오라는 의미 
## +      -> More than One
## 원     -> "원"

['1,000원', '300,000,000원']

In [8]:
# Spam 매일과 Non-spam 매일에 들어있는 숫자의 개수를 구해봅시다
spam["text"]

## 여기에 정규표현식을 이용한 함수를 만들어서 apply에 넣어주면 되겠죠?

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: text, Length: 5572, dtype: object

In [9]:
# 함수를 짜줍시다
def count_digit(x): # x가 하나의 메일 text가 된다 (lambda x: 의 x와 동일하다고 생각하면 된다)
    pure_digit = re.findall('[0-9]',x) 
    len_digit = len(pure_digit)
    return len_digit

In [10]:
# apply에 넣어줍시다
digit_0 = spam.loc[spam.target == 0]["text"].apply(count_digit)
digit_1 = spam.loc[spam.target == 1]["text"].apply(count_digit)

# 개수의 평균을 구해봅시다 -> spam 메일이 숫자가 많이 들어가 있군요
digit_0.mean(), digit_1.mean()

(0.2992746113989637, 15.759036144578314)

정리) 새로 배운거

1. np.where -> 퀀트에서도 많이 씀

2. Regular Expression

3. apply에 직접 짠 함수 넣기

## Machine Learning Basic 2

지난주 수업에 이어서 scikit-learn을 사용한 머신러닝을 배워보겠습니다

주가를 예측하는 간단한 머신러닝 모델을 만들어 보겠습니다

In [27]:
# 데이터셋을 불러오겠습니다
df = pd.read_csv("Data/coin_prediction.csv", index_col=0,
                  parse_dates=True)
df

# 고려할 점은 많지만, 단순화를 위해 복잡한 상황은 고려하지 않겠습니다(시계열이지만, 시계열로 보지 않겠습니다)
## 여러 변수로 다음날 BTC 가격을 예측하는 머신러닝 모델을 짜보겠습니다

BTC         NYSE        NASDAQ     LSE    BTC_Volume  \
Date                                                                       
2018-01-02  14982.09961  12902.71973   7006.899902  3742.0  1.684660e+10   
2018-01-03  15201.00000  12957.28027   7065.529785  3749.0  1.687190e+10   
2018-01-04  15599.20020  13028.45996   7077.910156  3749.0  2.178320e+10   
2018-01-05  17429.50000  13103.23047   7136.560059  3758.0  2.384090e+10   
2018-01-08  15170.09961  13114.34961   7157.390137  3744.0  1.841390e+10   
...                 ...          ...           ...     ...           ...   
2022-12-23  16796.95313  15188.45020  10497.860350  7130.0  1.532927e+10   
2022-12-27  16717.17383  15218.25977  10353.230470  7130.0  1.574858e+10   
2022-12-28  16552.57227  15037.32031  10213.290040  7128.0  1.700571e+10   
2022-12-29  16642.34180  15241.20996  10478.089840  7212.0  1.447224e+10   
2022-12-30  16602.58594  15184.30957  10466.480470  7136.0  1.592916e+10   

            NYSE_Volume  NASDAQ_Volume  LSE_Volume  
Date                                                
2018-01-02   3397430000     1929700000      497857  
2018-01-03   3544030000     2173130000     1009997  
2018-01-04   3697340000     2103220000      669448  
2018-01-05   3239280000     2024000000     2225274  
2018-01-08   3246160000     2055010000      930995  
...                 ...            ...         ...  
2022-12-23   2819280000     3544680000      141614  
2022-12-27   3030300000     3827290000      141614  
2022-12-28   3083520000     3842970000      490323  
2022-12-29   3003680000     4154100000      457006  
2022-12-30   2979870000     3959030000      226505  

[1259 rows x 8 columns]

In [31]:
df.BTC.pct_change().shift(-1)

Date
2018-01-02    0.014611
2018-01-03    0.026196
2018-01-04    0.117333
2018-01-05   -0.129631
2018-01-08   -0.037884
                ...   
2022-12-23   -0.004750
2022-12-27   -0.009846
2022-12-28    0.005423
2022-12-29   -0.002389
2022-12-30         NaN
Name: BTC, Length: 1259, dtype: float64

In [32]:
# 우선 정답지를 만들어 주겠습니다
## BTC가 "내일" 오르면 1, 내리면 0으로 정답을 설정하겠습니다
### shift(-1)로 다음날 수익을 정답으로 만들어야겠죠?
pct = df.BTC.pct_change().shift(-1)

# np.where로 조건을 줌 : 오르면 1, 내리면 0
y = np.where(pct > 0, 1, 0)
y

array([1, 1, 1, ..., 1, 0, 0])

In [34]:
# 정답의 비율을 확인해봅시다
## DataFrame이면 value_counts를 쓸 수 있지만, numpy array는 안됩니다 다른 방식으로 해볼까요?

## True, False를 Mean 해주면 True의 비율을 출력하겠죠?
(y == 1).mean(), (y==0).mean()

(0.5107227958697379, 0.4892772041302621)

In [37]:
df.iloc[:,1:]

NYSE        NASDAQ     LSE    BTC_Volume  NYSE_Volume  \
Date                                                                       
2018-01-02  12902.71973   7006.899902  3742.0  1.684660e+10   3397430000   
2018-01-03  12957.28027   7065.529785  3749.0  1.687190e+10   3544030000   
2018-01-04  13028.45996   7077.910156  3749.0  2.178320e+10   3697340000   
2018-01-05  13103.23047   7136.560059  3758.0  2.384090e+10   3239280000   
2018-01-08  13114.34961   7157.390137  3744.0  1.841390e+10   3246160000   
...                 ...           ...     ...           ...          ...   
2022-12-23  15188.45020  10497.860350  7130.0  1.532927e+10   2819280000   
2022-12-27  15218.25977  10353.230470  7130.0  1.574858e+10   3030300000   
2022-12-28  15037.32031  10213.290040  7128.0  1.700571e+10   3083520000   
2022-12-29  15241.20996  10478.089840  7212.0  1.447224e+10   3003680000   
2022-12-30  15184.30957  10466.480470  7136.0  1.592916e+10   2979870000   

            NASDAQ_Volume  LSE_Volume  
Date                                   
2018-01-02     1929700000      497857  
2018-01-03     2173130000     1009997  
2018-01-04     2103220000      669448  
2018-01-05     2024000000     2225274  
2018-01-08     2055010000      930995  
...                   ...         ...  
2022-12-23     3544680000      141614  
2022-12-27     3827290000      141614  
2022-12-28     3842970000      490323  
2022-12-29     4154100000      457006  
2022-12-30     3959030000      226505  

[1259 rows x 7 columns]

In [14]:
# 피쳐(Feature)도 분리하겠*습니다 (정답지랑 유사한 BTC 가격만 제거하겠습니다)
X = df.iloc[:, 1:]

In [38]:
X.shape, y.shape

((1259, 7), (1259,))

In [39]:
# 훈련셋과 테스트 셋 분리해주기
from sklearn.model_selection import train_test_split

## 시계열이라 Shuffle하면 안되겠죠? Shuffle=False로 지정해줍니다
X_train, X_test, y_train, y_test = train_test_split(X,y, shuffle=False) # default 0.75
X_train.shape, X_test.shape

((944, 7), (315, 7))

In [41]:
# 2018년 1월 ~ 2021년 9월 / 2021년 10월 ~ 2022년 12월까지 잘 분리한 것을 볼 수 있습니다
#X_train
X_test

NYSE       NASDAQ     LSE    BTC_Volume  NYSE_Volume  \
Date                                                                      
2021-10-01  16323.74023  14566.70020  7448.0  4.285064e+10   4010370000   
2021-10-04  16198.55957  14255.48047  7412.0  3.338317e+10   4307870000   
2021-10-05  16327.08984  14433.83008  7468.0  3.587390e+10   3902890000   
2021-10-06  16338.45996  14501.91016  7446.0  4.903473e+10   4009630000   
2021-10-07  16511.81055  14654.01953  7602.0  3.680786e+10   3843740000   
...                 ...          ...     ...           ...          ...   
2022-12-23  15188.45020  10497.86035  7130.0  1.532927e+10   2819280000   
2022-12-27  15218.25977  10353.23047  7130.0  1.574858e+10   3030300000   
2022-12-28  15037.32031  10213.29004  7128.0  1.700571e+10   3083520000   
2022-12-29  15241.20996  10478.08984  7212.0  1.447224e+10   3003680000   
2022-12-30  15184.30957  10466.48047  7136.0  1.592916e+10   2979870000   

            NASDAQ_Volume  LSE_Volume  
Date                                   
2021-10-01     4710720000      648683  
2021-10-04     4557110000      743863  
2021-10-05     4176390000      534997  
2021-10-06     4465910000      704478  
2021-10-07     3984180000      603144  
...                   ...         ...  
2022-12-23     3544680000      141614  
2022-12-27     3827290000      141614  
2022-12-28     3842970000      490323  
2022-12-29     4154100000      457006  
2022-12-30     3959030000      226505  

[315 rows x 7 columns]

In [42]:
# Feature Scaling 
## Standard Scaler로 정규화 해주겠습니다
from sklearn.preprocessing import StandardScaler

# 모델 만들고
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test) # fit 해주면 안됨!

In [47]:
# 머신러닝 모델을 만들고 예측해봅시다
## RandomForest 알고리즘을 사용하겠습니다
from sklearn.ensemble import RandomForestClassifier

# 모델 만들고, 학습해줌
## n_estimators: Tree 개수 , n_jobs : 사용할 프로세서의 수 (-1은 최대)
forest = RandomForestClassifier(n_estimators=1000, n_jobs=-1)
forest.fit(X_train_scaled, y_train)

RandomForestClassifier(n_estimators=1000, n_jobs=-1)

### 분류기 평가 Metric 


* 정확도 / 정밀도 / 재현율

In [48]:
# 분류기의 경우에 score는 단순한 정확도를 리턴 (accuracy score)
## 회귀의 경우에 score는 R^2를 리턴 했던거 기억나시죠?
forest.score(X_train_scaled, y_train)

1.0

In [50]:
# test 데이터에 대한 점수 출력 -> 확실히 overfit 되었군요
forest.score(X_test_scaled, y_test)

## 원래 이렇게 머신러닝 모델을 만드는 중간에 test-score를 구하면 안되지만, 수업 진행을 위해 구해봤습니다

0.4507936507936508

목표로 하는 task에 따라서 중요하게 생각해야하는 Metric이 달라진다 (통계학의 1종오류, 2종오류 개념과 유사)

여러 복잡한 Metric이 많지만 (F1-score, ROC-AUC 등등...) 단순한 3가지만 배워보겠습니다.

* 정확도(Accuracy)  : 전체 데이터 수 중 예측 결과와 실제 값이 동일한 건수(TN + TP)가 차지하는 비율, 가장 포괄적인 값이라 생각하면 됨

* 정밀도(Precision) : 예측을 Positive로 한 대상(FP + TP) 중 예측과 실제 값이 Positive로 일치한 데이터(TP)의 비율

* 재현율(Recall) : 실제가 Positive인 대상(FN + TP) 중 예측과 실제 값이 Positive로 일치한 데이터(TP)의 비율



In [51]:
# 우선 아래 평가를 위해 모델의 예측값을 저장하겠습니다
y_predict = forest.predict(X_test_scaled)
y_predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,

In [52]:
# 정밀도와 재현율을 구해보겠습니다

from sklearn.metrics import precision_score, recall_score

print("모델의 정확도: ", forest.score(X_test_scaled, y_test))
print("모델의 정밀도: ", precision_score(y_test, y_predict))
print("모델의 재현율: ", recall_score(y_test, y_predict))

모델의 정확도:  0.4507936507936508
모델의 정밀도:  0.444015444015444
모델의 재현율:  0.7986111111111112


### Cross-Validation

* Test-set을 미리 들여다 보는 우를 범하지 않기 위해 사용함

<img src="https://scikit-learn.org/stable/_images/grid_search_cross_validation.png" width="700" height="300"/>

In [53]:
from sklearn.model_selection import cross_val_score

# cv=5이면 데이터를 5번 쪼갠다. 데이터는 반드시 Random해야 한다!
## cross_val_score(훈련할 모델, X, y)
## verb
forest = RandomForestClassifier()
cv_score = cross_val_score(forest, X_train_scaled, y_train, 
                           cv=5, n_jobs=-1)

In [55]:
# 각각의 값이 CV의 score(정확도)입니다.
print(cv_score)

# cv_score의 평균
cv_score.mean()

## 아까 우리가 구했던 test 데이터에 대한 정확도와 cv의 평균 정확도가 유사한게 신기하지 않으신가요?

[0.51322751 0.44973545 0.38095238 0.47619048 0.52659574]


0.46934031295733425

### Grid-Search 

격자 탐색 : 가장 성능이 좋은 하이퍼파라미터를 찾는다

Overfitting 방지를 위해 그리드 서치 중에 Cross-Validation 방식으로 평가해야 한다

In [56]:
# 그리드 서치를 import 한다
from sklearn.model_selection import GridSearchCV

# 사용할 모델인 Support Vector Machine을 임포트하고, 모델을 만들겠습니다
from sklearn.svm import SVC
svc = SVC() # 아직 fit해주진 않음!

# 그리드 서치를 진행할 딕셔너리를 정의해줍시다 
param_grid = {"C" : [0.01, 1, 10, 100],  
              'kernel': ["linear","poly", "rbf"]} 

# 그리드 서치를 수행합니다. (verbose=True면 중간중간 진행 상황을 출력합니다)
grid_model = GridSearchCV(svc, param_grid, 
                         cv=5, verbose=True, n_jobs=-1)

grid_model.fit(X_train_scaled, y_train)

# 최고의 cv 점수를 기록한 파라미터 조합을 출력합니다
grid_model.best_params_

Fitting 5 folds for each of 12 candidates, totalling 60 fits


{'C': 0.01, 'kernel': 'rbf'}

In [57]:
# train set에 대한 점수를 구해봅시다
grid_model.score(X_train_scaled, y_train)

0.5286016949152542